SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
--
-- Databáze: `test`

CREATE TABLE `country` (
  `id` int(11) NOT NULL,
  `country` varchar(255) NOT NULL,
  `capital` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `country` (`id`, `country`, `capital`) VALUES
(1, 'afghanistan', 'kabul'),
(2, 'albania', 'tirana'),
(3, 'algeria', 'algiers'),
(4, 'andorra', 'andorra la vella'),
(5, 'angola', 'luanda'),
(6, 'antigua and barbuda', 'saint john\'s'),
(7, 'argentina', 'buenos aires'),
(8, 'armenia', 'yerevan'),
(9, 'australia', 'canberra'),
(10, 'austria', 'vienna'),
(11, 'azerbaijan', 'baku'),
(12, 'the bahamas', 'nassau'),
(13, 'bahrain', 'manama'),
(14, 'bangladesh', 'dhaka'),
(15, 'barbados', 'bridgetown'),
(16, 'belarus', 'minsk'),
(17, 'belgium', 'brussels'),
(18, 'belize', 'belmopan'),
(19, 'benin', 'porto-novo'),
(20, 'bhutan', 'thimphu'),
(21, 'bolivia', 'la paz (administrative); sucre (judicial)'),
(22, 'bosnia and herzegovina', 'sarajevo'),
(23, 'botswana', 'gaborone'),
(24, 'brazil', 'brasilia'),
(25, 'brunei', 'bandar seri begawan'),
(26, 'bulgaria', 'sofia'),
(27, 'burkina faso', 'ouagadougou'),
(28, 'burundi', 'gitega (changed from bujumbura in december 2018)'),
(29, 'cambodia', 'phnom penh'),
(30, 'cameroon', 'yaounde'),
(31, 'canada', 'ottawa'),
(32, 'cape verde', 'praia'),
(33, 'central african republic', 'bangui'),
(34, 'chad', 'n\'djamena'),
(35, 'chile', 'santiago'),
(36, 'china', 'beijing'),
(37, 'colombia', 'bogota'),
(38, 'comoros', 'moroni'),
(39, 'congo, republic of the', 'brazzaville'),
(40, 'congo, democratic republic of the', 'kinshasa'),
(41, 'costa rica', 'san jose'),
(42, 'cote d\'ivoire', 'yamoussoukro (official); abidjan (de facto)'),
(43, 'croatia', 'zagreb'),
(44, 'cuba', 'havana'),
(45, 'cyprus', 'nicosia'),
(46, 'czech republic', 'prague'),
(47, 'denmark', 'copenhagen'),
(48, 'djibouti', 'djibouti'),
(49, 'dominica', 'roseau'),
(50, 'dominican republic', 'santo domingo'),
(51, 'east timor (timor-leste)', 'dili'),
(52, 'ecuador', 'quito'),
(53, 'egypt', 'cairo'),
(54, 'el salvador', 'san salvador'),
(55, 'equatorial guinea', 'malabo'),
(56, 'eritrea', 'asmara'),
(57, 'estonia', 'tallinn'),
(58, 'ethiopia', 'addis ababa'),
(59, 'fiji', 'suva'),
(60, 'finland', 'helsinki'),
(61, 'france', 'paris'),
(62, 'gabon', 'libreville'),
(63, 'the gambia', 'banjul'),
(64, 'georgia', 'tbilisi'),
(65, 'germany', 'berlin'),
(66, 'ghana', 'accra'),
(67, 'greece', 'athens'),
(68, 'grenada', 'saint george\'s'),
(69, 'guatemala', 'guatemala city'),
(70, 'guinea', 'conakry'),
(71, 'guinea-bissau', 'bissau'),
(72, 'guyana', 'georgetown'),
(73, 'haiti', 'port-au-prince'),
(74, 'honduras', 'tegucigalpa'),
(75, 'hungary', 'budapest'),
(76, 'iceland', 'reykjavik'),
(77, 'india', 'new delhi'),
(78, 'indonesia', 'jakarta'),
(79, 'iran', 'tehran'),
(80, 'iraq', 'baghdad'),
(81, 'ireland', 'dublin'),
(82, 'israel', 'jerusalem*'),
(83, 'italy', 'rome'),
(84, 'jamaica', 'kingston'),
(85, 'japan', 'tokyo'),
(86, 'jordan', 'amman'),
(87, 'kazakhstan', 'astana'),
(88, 'kenya', 'nairobi'),
(89, 'kiribati', 'tarawa atoll'),
(90, 'korea, north', 'pyongyang'),
(91, 'korea, south', 'seoul'),
(92, 'kosovo', 'pristina'),
(93, 'kuwait', 'kuwait city'),
(94, 'kyrgyzstan', 'bishkek'),
(95, 'laos', 'vientiane'),
(96, 'latvia', 'riga'),
(97, 'lebanon', 'beirut'),
(98, 'lesotho', 'maseru'),
(99, 'liberia', 'monrovia'),
(100, 'libya', 'tripoli'),
(101, 'liechtenstein', 'vaduz'),
(102, 'lithuania', 'vilnius'),
(103, 'luxembourg', 'luxembourg'),
(104, 'macedonia', 'skopje'),
(105, 'madagascar', 'antananarivo'),
(106, 'malawi', 'lilongwe'),
(107, 'malaysia', 'kuala lumpur'),
(108, 'maldives', 'male'),
(109, 'mali', 'bamako'),
(110, 'malta', 'valletta'),
(111, 'marshall islands', 'majuro'),
(112, 'mauritania', 'nouakchott'),
(113, 'mauritius', 'port louis'),
(114, 'mexico', 'mexico city'),
(115, 'micronesia, federated states of', 'palikir'),
(116, 'moldova', 'chisinau'),
(117, 'monaco', 'monaco'),
(118, 'mongolia', 'ulaanbaatar'),
(119, 'montenegro', 'podgorica'),
(120, 'morocco', 'rabat'),
(121, 'mozambique', 'maputo'),
(122, 'Myanmar (Burma)', 'Rangoon (Yangon); Naypyidaw or Nay Pyi Taw (administrative)'),
(123, 'namibia', 'windhoek'),
(124, 'nauru', 'no official `capital`; government offices in yaren district'),
(125, 'nepal', 'kathmandu'),
(126, 'netherlands', 'amsterdam; the hague (seat of government)'),
(127, 'new zealand', 'wellington'),
(128, 'nicaragua', 'managua'),
(129, 'niger', 'niamey'),
(130, 'nigeria', 'abuja'),
(131, 'norway', 'oslo'),
(132, 'oman', 'muscat'),
(133, 'pakistan', 'islamabad'),
(134, 'palau', 'melekeok'),
(135, 'panama', 'panama city'),
(136, 'papua new guinea', 'port moresby'),
(137, 'paraguay', 'asuncion'),
(138, 'peru', 'lima'),
(139, 'philippines', 'manila'),
(140, 'poland', 'warsaw'),
(141, 'portugal', 'lisbon'),
(142, 'qatar', 'doha'),
(143, 'romania', 'bucharest'),
(144, 'russia', 'moscow'),
(145, 'rwanda', 'kigali'),
(146, 'saint kitts and nevis', 'basseterre'),
(147, 'saint lucia', 'castries'),
(148, 'saint vincent and the grenadines', 'kingstown'),
(149, 'samoa', 'apia'),
(150, 'san marino', 'san marino'),
(151, 'sao tome and principe', 'sao tome'),
(152, 'saudi arabia', 'riyadh'),
(153, 'senegal', 'dakar'),
(154, 'serbia', 'belgrade'),
(155, 'seychelles', 'victoria'),
(156, 'sierra leone', 'freetown'),
(157, 'singapore', 'singapore'),
(158, 'slovakia', 'bratislava'),
(159, 'slovenia', 'ljubljana'),
(160, 'solomon islands', 'honiara'),
(161, 'somalia', 'mogadishu'),
(162, 'South Africa', 'Pretoria (administrative); Cape Town (legislative); Bloemfontein (judiciary)'),
(163, 'south sudan', 'juba'),
(164, 'spain', 'madrid'),
(165, 'sri lanka', 'colombo; sri jayewardenepura kotte (legislative)'),
(166, 'sudan', 'khartoum'),
(167, 'suriname', 'paramaribo'),
(168, 'swaziland', 'mbabane'),
(169, 'sweden', 'stockholm'),
(170, 'switzerland', 'bern'),
(171, 'syria', 'damascus'),
(172, 'taiwan', 'taipei'),
(173, 'tajikistan', 'dushanbe'),
(174, 'tanzania', 'dar es salaam; dodoma (legislative)'),
(175, 'thailand', 'bangkok'),
(176, 'togo', 'lome'),
(177, 'tonga', 'nuku\'alofa'),
(178, 'trinidad and tobago', 'port-of-spain'),
(179, 'tunisia', 'tunis'),
(180, 'turkey', 'ankara'),
(181, 'turkmenistan', 'ashgabat'),
(182, 'tuvalu', 'vaiaku village, funafuti province'),
(183, 'uganda', 'kampala'),
(184, 'ukraine', 'kyiv'),
(185, 'united arab emirates', 'abu dhabi'),
(186, 'united kingdom', 'london'),
(187, 'united states of america', 'washington, d.c.'),
(188, 'uruguay', 'montevideo'),
(189, 'uzbekistan', 'tashkent'),
(190, 'vanuatu', 'port-vila'),
(191, 'vatican city (holy see)', 'vatican city'),
(192, 'venezuela', 'caracas'),
(193, 'vietnam', 'hanoi'),
(194, 'yemen', 'sanaa'),
(195, 'zambia', 'lusaka'),
(196, 'zimbabwe', 'harare');

ALTER TABLE `country`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `country`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=197;
COMMIT;